### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by angvp** [miki725/django-url-filter-deprecated#2]
$ pip install django-url-filter==dev

Downloading/unpacking django-url-filter
  Could not find any downloads that satisfy the requirement django-url-filter
  Some externally hosted files were ignored (use --allow-external django-url-filter to allow).
Cleaning up...
No distributions at all found for django-url-filter

**Comment by miki725** [comment]
this library was never published and was in development. at some point it needed a rewrite hence the new "deprecated status". please take a look at https://github.com/miki725/django-url-filter instead which is published now on PyPI
